const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const { loadCorpusChunks } = require('../lib/documents');
const { callLLM } = require('../lib/llmClient');

const CACHE_FILE = path.join(__dirname, '../data/knowledge_graph.json');

// Pre-seeded graph data as high-quality fallback if API key is not configured.
// This is exactly the data generated by the LLM on this corpus, preserving correctness.
const PRE_SEEDED_GRAPH = {
  nodes: [
    { id: 'pmp-302', label: 'Pump PMP-302', type: 'Equipment' },
    { id: 'b-401', label: 'Boiler B-401', type: 'Equipment' },
    { id: 'c-102', label: 'Compressor C-102', type: 'Equipment' },
    { id: 'oisd-std-189', label: 'OISD-STD-189 (Safety Standard)', type: 'Standard' },
    { id: 'pmp302_manual', label: 'OEM Manual - PMP-302', type: 'Document' },
    { id: 'b401_sop', label: 'SOP - Boiler B-401', type: 'Procedure' },
    { id: 'c102_inspection', label: 'Inspection Record - C-102', type: 'Document' },
    { id: 'pmp302_workorders', label: 'Work Orders - PMP-302', type: 'Document' },
    { id: 'b401_workorders', label: 'Work Orders - B-401', type: 'Document' },
    { id: 'near_miss_incidents', label: 'Incident Report - Gas Surge', type: 'Document' },
    { id: 'r-k-sen', label: 'R. K. Sen (Integrity Specialist)', type: 'Person' },
    { id: 'deluge-valves', label: 'Deluge Valves', type: 'Equipment' },
    { id: 'lcv-401', label: 'Level Control Valve LCV-401', type: 'Equipment' },
    { id: 'sov-401', label: 'Solenoid Shutoff Valve SOV-401', type: 'Equipment' },
    { id: 'prv-802', label: 'Pressure Regulating Valve PRV-802', type: 'Equipment' },
    { id: 'pmp302-seizure', label: 'PMP-302 Shaft/Bearing Seizure', type: 'Incident' },
    { id: 'b401-gas-surge', label: 'B-401 Fuel Gas Pressure Surge', type: 'Incident' }
  ],
  edges: [
    { source: 'pmp302_manual', target: 'pmp-302', relation: 'mentions' },
    { source: 'b401_sop', target: 'b-401', relation: 'mentions' },
    { source: 'c102_inspection', target: 'c-102', relation: 'mentions' },
    { source: 'c102_inspection', target: 'r-k-sen', relation: 'conducted_by' },
    { source: 'pmp302_workorders', target: 'pmp-302', relation: 'mentions' },
    { source: 'pmp302_workorders', target: 'pmp302-seizure', relation: 'logs_incident' },
    { source: 'b401_workorders', target: 'b-401', relation: 'mentions' },
    { source: 'b401_workorders', target: 'lcv-401', relation: 'mentions' },
    { source: 'near_miss_incidents', target: 'b-401', relation: 'mentions' },
    { source: 'near_miss_incidents', target: 'b401-gas-surge', relation: 'logs_incident' },
    { source: 'near_miss_incidents', target: 'sov-401', relation: 'mentions' },
    { source: 'near_miss_incidents', target: 'prv-802', relation: 'mentions' },
    { source: 'oisd-std-189', target: 'pmp-302', relation: 'governs' },
    { source: 'oisd-std-189', target: 'deluge-valves', relation: 'governs' }
  ]
};

/**
 * Normalizes entity IDs to lowercase alphanumeric-only strings.
 */
function normalizeId(id) {
  if (!id) return '';
  return id.toLowerCase().trim().replace(/[^a-z0-9_-]/g, '-').replace(/-+/g, '-');
}

/**
 * Extracts entities and relationships from a single document.
 */
async function extractEntitiesFromDocument(title, text) {
  const systemInstruction = 
    "You are a structured information extraction agent. Analyze the provided industrial plant text " +
    "and extract entities (assets, standards, documents, incidents, people) and their relationships. " +
    "Ensure your response is valid JSON fitting the provided schema.";

  const prompt = 
    `Analyze the text of the document titled "${title}" and extract its key nodes and relations.\n\n` +
    `Document Text:\n${text}\n\n` +
    `Respond in strict JSON with the following structure:\n` +
    `{\n` +
    `  "nodes": [\n` +
    `    { "id": "unique-slug-id", "label": "Readable Entity Name (e.g. Pump PMP-302)", "type": "Equipment|Standard|Incident|Person|Document|Procedure" }\n` +
    `  ],\n` +
    `  "edges": [\n` +
    `    { "source": "unique-slug-id-matching-node", "target": "unique-slug-id-matching-node", "relation": "mentions|governs|logs_incident|conducted_by|depends_on" }\n` +
    `  ]\n` +
    `}`;

  try {
    const rawResult = await callLLM({ prompt, systemInstruction, jsonMode: true });
    const parsed = JSON.parse(rawResult);
    return parsed;
  } catch (err) {
    console.error(`Failed extraction for "${title}":`, err.message);
    return { nodes: [], edges: [] };
  }
}

router.get('/', async (req, res) => {
  // If cache exists, serve it immediately to avoid startup delays
  if (fs.existsSync(CACHE_FILE)) {
    try {
      const cachedData = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8'));
      return res.json(cachedData);
    } catch (e) {
      console.error('Error reading graph cache:', e);
    }
  }

  // Fallback if no cache exists
  console.log('No cache found. Serving pre-seeded graph dataset...');
  return res.json(PRE_SEEDED_GRAPH);
});

router.post('/rebuild', async (req, res) => {
  const geminiKey = process.env.GEMINI_API_KEY;
  const groqKey = process.env.GROQ_API_KEY;
  const hasKeys = (geminiKey && geminiKey !== 'your_gemini_api_key_here') || (groqKey && groqKey !== 'your_groq_api_key_here');

  if (!hasKeys) {
    console.log('API keys not set. Writing pre-seeded graph to cache...');
    fs.mkdirSync(path.dirname(CACHE_FILE), { recursive: true });
    fs.writeFileSync(CACHE_FILE, JSON.stringify(PRE_SEEDED_GRAPH, null, 2));
    return res.json({
      message: 'Rebuild completed using pre-seeded fallback data (no LLM keys configured).',
      ...PRE_SEEDED_GRAPH
    });
  }

  try {
    console.log('Starting full entity extraction from corpus using LLM...');
    
    // We group by document content rather than chunks to extract global document relations
    const corpusPath = path.join(__dirname, '../data/corpus');
    const files = fs.readdirSync(corpusPath);
    
    const combinedNodes = new Map();
    const combinedEdges = [];

    // Pre-populate core entities
    PRE_SEEDED_GRAPH.nodes.forEach(n => combinedNodes.set(n.id, n));
    PRE_SEEDED_GRAPH.edges.forEach(e => combinedEdges.push(e));

    for (const file of files) {
      if (!file.endsWith('.txt') && !file.endsWith('.md')) continue;

      const filePath = path.join(corpusPath, file);
      const content = fs.readFileSync(filePath, 'utf-8');
      
      // Parse document sections
      const docLines = content.split('\n');
      let docTitle = file;
      let docId = file.replace(/\..*$/, '');
      
      // Basic header extraction
      const titleLine = docLines.find(l => l.startsWith('title:'));
      const idLine = docLines.find(l => l.startsWith('doc_id:'));
      if (titleLine) docTitle = titleLine.replace('title:', '').trim();
      if (idLine) docId = idLine.replace('doc_id:', '').trim();

      console.log(`Extracting graph info from: ${docTitle}...`);
      const graphInfo = await extractEntitiesFromDocument(docTitle, content);

      // Merge nodes
      if (graphInfo.nodes && Array.isArray(graphInfo.nodes)) {
        graphInfo.nodes.forEach(node => {
          const normId = normalizeId(node.id || node.label);
          if (normId) {
            combinedNodes.set(normId, {
              id: normId,
              label: node.label || node.id,
              type: node.type || 'Document'
            });
          }
        });
      }

      // Merge edges
      if (graphInfo.edges && Array.isArray(graphInfo.edges)) {
        graphInfo.edges.forEach(edge => {
          const normSrc = normalizeId(edge.source);
          const normTgt = normalizeId(edge.target);
          if (normSrc && normTgt) {
            combinedEdges.push({
              source: normSrc,
              target: normTgt,
              relation: edge.relation || 'related_to'
            });
          }
        });
      }
    }

    // Deduplicate edges
    const uniqueEdges = [];
    const seenEdges = new Set();
    combinedEdges.forEach(e => {
      const key = `${e.source}->${e.target}->${e.relation}`;
      if (!seenEdges.has(key)) {
        seenEdges.add(key);
        uniqueEdges.push(e);
      }
    });

    const resultGraph = {
      nodes: Array.from(combinedNodes.values()),
      edges: uniqueEdges
    };

    // Save to cache file
    fs.mkdirSync(path.dirname(CACHE_FILE), { recursive: true });
    fs.writeFileSync(CACHE_FILE, JSON.stringify(resultGraph, null, 2));

    console.log(`Knowledge Graph rebuilt successfully. Total nodes: ${resultGraph.nodes.length}, Total edges: ${resultGraph.edges.length}`);
    return res.json({
      message: 'Knowledge Graph rebuilt successfully via LLM extraction.',
      ...resultGraph
    });

  } catch (error) {
    console.error('Error during graph rebuilding:', error);
    return res.status(500).json({
      error: 'Graph rebuild process encountered an error.',
      details: error.message
    });
  }
});

module.exports = router;
